// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxuXVHiFGVJYxR_RuzXnFy-zeHoI9Llwk',
    appId: '1:861648813622:web:02a0941a85530bb1b4e297',
    messagingSenderId: '861648813622',
    projectId: 'dairy2-faa38',
    authDomain: 'dairy2-faa38.firebaseapp.com',
    storageBucket: 'dairy2-faa38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2UZbi_HvAYpYcoZZbdDJORp1xVZLWYz4',
    appId: '1:861648813622:android:2a75156147d128deb4e297',
    messagingSenderId: '861648813622',
    projectId: 'dairy2-faa38',
    storageBucket: 'dairy2-faa38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-4lVuWAp2QogkHHLz8dveRD6R6Vu_18',
    appId: '1:861648813622:ios:cc1c182b12105c0cb4e297',
    messagingSenderId: '861648813622',
    projectId: 'dairy2-faa38',
    storageBucket: 'dairy2-faa38.appspot.com',
    iosClientId: '861648813622-46tkm67l69s0a25bnkasq8dtr2btmmdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7-4lVuWAp2QogkHHLz8dveRD6R6Vu_18',
    appId: '1:861648813622:ios:cc1c182b12105c0cb4e297',
    messagingSenderId: '861648813622',
    projectId: 'dairy2-faa38',
    storageBucket: 'dairy2-faa38.appspot.com',
    iosClientId: '861648813622-46tkm67l69s0a25bnkasq8dtr2btmmdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myDairy',
  );
}
